# -*- coding: utf-8 -*-
"""module4.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1BMbyxYwZFiilOCgGK3WN4mrTj3uFU1uw
"""

# Ask for the number of elements
N = int(input("Enter a positive integer (N): "))

# Initialize an empty list to store the numbers
numbers = []

# Ask the user to input N numbers, one by one
print(f"Enter {N} numbers:")
for i in range(N):
    num = int(input(f"Number {i + 1}: "))
    numbers.append(num)

# Ask for an additional integer X
X = int(input("Enter the integer X to find in the list: "))

# Check if X is in the list and output the index (1-based) or -1
if X in numbers:
    index = numbers.index(X) + 1  # Convert 0-based index to 1-based
    print(index)
else:
    print("-1")